name: DEPLOY

on :
    workflow_run:
        workflows: [CI]
        types: 
            - completed
    
jobs:
    push-to-dockerhub:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        
        steps:
            - name: copy repository
              uses: actions/checkout@v4
             
            - name: login to dockehub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: build and push to docker hub
              uses: docker/build-push-action@v5
              with:
                context: ./backend
                push: true
                tags: ${{secrets.DOCKERHUB_USERNAME}}:lawyermanagement:latest




